name: Publish to npm

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: Bump the project version then publish to npm
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node_version: 22
      - name: Bump package version
        run: npm version --no-commit-hooks --no-git-tag-version ${{github.event.inputs.release_type}}
      - name: Build package
        run: |
           npm clean-install
           npm run build
      - name: Configure git user
        run: |
          git config user.email "${{github.actor}}@users.noreply.github.com"
          git config user.name "${{github.actor}}"
      - name: Commit change
        run: |
          git add package.json
          git commit -m "package version bump to $(npm pkg get version | tr -d '"')"
      - name: Create git version tag
        run: git tag "v$(npm pkg get version | tr -d '"')"
      - name: Push changes
        run: |
          git push --tags origin
          git push
      - name: Publish to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
